[book]
authors = ["chenxizhan"]
language = "zh-CN"
multilingual = false
src = "src"
title = "java-note"

[output.html]
site-url="https://github.com/chenxizhan1995/java-note.git"
git-repository-url="https://github.com/chenxizhan1995/java-note.git"
[output.html.fold]
enable=true
level=1
